### PR TITLE
Apply fixes from Keith via E-Mail

### PR DESCRIPTION
**Pull request by t-b**
This allows us to use NWB custom datasets.

### CODE REVIEW

**Comment by campagnola** [comment]
@nicain this fix is currently in use by the multipatch pipeline. Is it worth merging it here, or should we just continue to use our own fork?

**Comment by nicain** [comment]
@campagnola since this fork was deprecated back on Jan. 9th (and therefore off my radar) via https://github.com/AllenInstitute/nwb-api/commit/399a7a70b17e5cc308b7925d87e4c963644b6814, I say not worth merging, and continue to use your fork.  Is your fork maintained on Stash?  I say stick with whatever works for you internally.

**Comment by nicain** [comment]
Closed as this fork is currently deprecated; please see https://github.com/AllenInstitute/nwb-api/blob/master/README.md.

**Comment by t-b** [comment]
@campagnola @nicain We are currently using my fork of this project last time I checked. So we can just continue to do that until we move to NWB v2 and pynwb.

**Pull request closed without merging**
